asfadmin/Discovery-asf_search

- CHANGELOG.md
- asf_search/ASFSearchResults.py
- asf_search/__init__.py
- asf_search/search/search.py
- Parallel downloads now supported by ASFSearchResults. Defaults to 1 (sequential download)
- Import download functionality in asf_search (for `download_url()`)
- Fixed ASFProduct import in search.py
> Parallel download support

- asf_search/__init__.py
- asf_search/download/download.py
- asf_search/search/search.py
- setup.py
`importlib.metadata` is only available for python 3.8+, but the `importlib_metadata` package backports the functionality for python <3.8.
This will fix `asf_search` for python <3.8. 
I've also made it so the package version only needs to be resolved once, but **I've removed** setting a default version to `0.0.0` so the package will *have to be installed* if cloned directly (via `python -m pip install -e .`). I think this is preferable, personally, as you'll always get the right package version in your headers, but it does require developers to install the package.
Previous functionality could be restored by issuing a `UserWarning` with the currently printed message and setting `__version__ = 0.0.0' during exception handling if desired. …
> imporlib_metdata fixes for python < 3.8

- CHANGELOG.md
- README.md
- asf_search/ASFProduct.py
- asf_search/ASFSearchResults.py
- asf_search/ASFSession.py
- asf_search/__init__.py
- asf_search/constants/INTERNAL.py
- asf_search/constants/__init__.py
- asf_search/download/__init__.py
- asf_search/download/download.py
- asf_search/exceptions.py
- asf_search/health/health.py
- asf_search/search/baseline_search.py
- asf_search/search/geo_search.py
- asf_search/search/granule_search.py
- asf_search/search/product_search.py
- asf_search/search/search.py
requests documentation says the .netrc file is loaded automatically, if you don't add auth yourself. (For us, just calling download_url without passing a session). I can't yet get it working with redirects, but we're close to that too.
I wrote a draft in the changelog, but it might be wordy. Feel free to edit it too if you notice anything.
Thanks!
> Feature auth download - Cookies, user/pass supported

- CHANGELOG.md
- asf_search/download/download.py
Don't re-use established session if a download redirect goes direct to S3, just do a bare request. That way, we can still ensure thread safety since we won't need to mangle the session to get that redirect to work without S3 errors.
> Don't re-use established session if a download redirect goes direct to S3

- asf_search/ASFProduct.py
- asf_search/search/baseline_search.py
- setup.py
I was getting different results back from `asf_search.baseline_search` vs in Vertex and it appears to have come down to the way  `ASFProduct.centroid` is calculated. Examples:
where the green diamond is the scene's center (`centerLon`, `centerLat`) as defined in the metadata, black circle is using shapely, and red circle is the existing numpy implementation.
This drops numpy as a requirement (only used by centroid) and adds shapely. 
---
An alternative approach, once [`centerLon` and `centerLat` are in the GeoJSON properties](https://github.com/asfadmin/Discovery-SearchAPI/commit/51bacc2055fd7e6f0acf60843af7e33901b17d79), would be to leverage those instead, assuming that's available for all product types. 
* could either drop the centroid function or return `(self.properties['centerLon'], …
> Use shapely to calculate centroid

- asf_search/download/download.py
When attempting to download, do not raise an exception if the file already exists, emit a warning instead and skip that file.
> Skip download if file already exists

- asf_search/CMR/__init__.py
- asf_search/__init__.py
adds missing __init__.py for asf_search.CMR module, imports to asf_search module
> Missing CMR Module hotfix

- CHANGELOG.md
- asf_search/CMR/__init__.py
- asf_search/__init__.py
- Fixes missing CMR module import
> Missing CMR-Module Hotfix

- CHANGELOG.md
- asf_search/baseline/calc.py
- asf_search/baseline/stack.py
- `ASFProduct.stack()` and `asf_search.baseline_search.stack_from_id()` now return ASFSearchResults instead of a list
------
> Hotfix: calculate_perpendicular_baselines() now returns ASFSearchResults

- CHANGELOG.md
- asf_search/baseline/calc.py
- asf_search/baseline/stack.py
(Addresses issue #100 )
- `ASFProduct.Download()` works with .netrc credentials again
------
> Bugfix: restores netrc fallback authentication on ASFProduct.Download()

- asf_search/ASFProduct.py
- asf_search/CMR/translate.py
Allows pretty much everything to be optional in the ASFProduct constructor. Although such an object will be largely useless, it should allow extremely light-weight testing in some use cases, and also be more resilient against malformed CMR records.
> Barebones product support

- asf_search/ASFProduct.py
We're letting literally everything else be empty at this point, so we might as well go this extra step.
> Allow empty ASFProduct instantiation

- CHANGELOG.md
- asf_search/CMR/translate.py
- non-rectangular polygons are now sent to CMR instead of their bounding boxes
> Fix Polygon Bounding Box bug

- asf_search/search/search.py
CMR's default results sorting was used while testing export feature. This restores sorting to end of `search()`
> Sorts results again at end of search()

- CHANGELOG.md
- asf_search/constants/INTERNAL.py
- `CMR_PAGE_SIZE` reduced from 2000 to 500
> V5.1.1 Page Size Reduced to 500

- CHANGELOG.md
PR to prepare master branch changelog for stable release
- Search errors are now automatically reported to ASF, users can opt out by changing `asf_search.REPORT_ERRORS` after import
- Example and information available in "Usage" section of /examples/1-Basic_Overview.ipynb
- `ASFSearchResults` now has `raise_if_incomplete()` method, raises `ASFSearchError()` if a search encountered an error and was unable to return all results from CMR
- `ASFProduct` now has a `remotezip()` method, which takes a user's pre-authenticated `ASFSession` and returns a `RemoteZip` object. This can be used to list and download specific files from a product's zip archive, rather than the whole zip file. 
- Example available in /examples/5-Download.ipynb
- see https://github.com/gtsystem/python-remotezip for …
> 6.0.0 Release Changelog

- .github/workflows/run-pytest.yml
- bumps codecov version from 2 to 3
- set `fail_ci_if_error` flag to false (would cause workflow to fail if error encountered with uploading coverage)
> Codecov Python Workflow Update

- CHANGELOG.md
- asf_search/ASFProduct.py
- tests/ASFProduct/test_ASFProduct.py
- tests/download/test_download.py
- tests/pytest-config.yml
- tests/pytest-managers.py
- tests/yml_tests/test_ASFProduct.yml
- filename works with ASFProduct.download() again
- warns user if downloading multiple files and `filename` is specified, then ignores `filename`
> Bugfix: ASFProduct.Download() filename keyword fix

- CHANGELOG.md
- asf_search/search/search_generator.py
- fixes breaking change added to search_generator caused by list type hinting
- `list[ASFproduct]` only supported in python versions >= 3.9
> BUGFIX: python V3.8 Unsupported Type Hinting

- CHANGELOG.md
- asf_search/CMR/translate.py
- ERS-1, ERS-2, JERS-1, and RADARSAT-1 now assign `FRAME_NUMBER` to the `frameNumber` properties field
> Certain Platforms now use FRAME_NUMBER (ERS, JERS, RADARSAT)

- asf_search/ASFSearchOptions/ASFSearchOptions.py
I ran into this error and it looks like there is an open issue for it already here https://github.com/asfadmin/Discovery-asf_search/issues/226
This fixes the problem, I was able to jump to the logger warning method definition once the change was applied.
> fix asf logger method name error

- CHANGELOG.md
- asf_search/CMR/translate.py
Inconsistency between `datetime.timestamp()` across systems causes `timestamp()` to infer different timezones for date objects. Baseline calculations depends on these values, and when certain product baseline values lacked the timezone indicator it'd lead to bad baseline values depending on the system environment.
Solution:
- appends 'Z' to S1 baseline date properties if missing (ascending node time, sv times, etc)
> S1 Baseline Stacking Fix

- asf_search/ASFProduct.py
- asf_search/ASFSearchResults.py
- asf_search/Products/ARIAS1GUNWProduct.py
- asf_search/Products/OPERAS1Product.py
- asf_search/Products/S1Product.py
- asf_search/baseline/stack.py
- asf_search/search/baseline_search.py
- examples/Advanced-Custom-ASFProduct-Subclassing.ipynb
- Adds `useSubclass` param to baseline search methods, converts reference and stack search results to given `ASFProduct` subclass prior to baseline stacking operations
> Adds subproduct class type casting to baseline_search

- CHANGELOG.md
- asf_search/ASFSession.py
- tests/ASFSession/test_ASFSession.py
- Improved logging in `ASFSession` authentication methods
- `ASFSession` now allows for authorized user access to hidden/restricted CMR datasets via `auth_with_creds()` or `auth_with_cookiejar()` authentication methods (previously only supported via `auth_with_token()` method)
- `ASFSession.auth_with_token()` now authenticates directly against EDL endpoint
> ASFSession Hidden/Restricted Dataset Access Normalization

- CHANGELOG.md
- asf_search/CMR/translate.py
- setup.py
- tests/ASFSearchResults/test_ASFSearchResults.py
- uses `ciso8601` for umm result date parsing
- bumps from patch to minor version for release
> `ciso8601` Result Date Parsing

- CHANGELOG.md
- asf_search/baseline/calc.py
- asf_search/baseline/stack.py
- setup.py
- Uses `ciso8601.parse_datetime()` in baseline calculations, speeds up calculations on larger stacks
> ciso8601 in baseline stacking

- CHANGELOG.md
- asf_search/ASFProduct.py
- asf_search/Products/ARIAS1GUNWProduct.py
- asf_search/Products/OPERAS1Product.py
- asf_search/search/baseline_search.py
- asf_search/search/search_generator.py
- `OPERAS1Product` now assigned to results by checking meta `collection-concept-id` field
- Adds `_is_subclass()` static method to `ASFProduct`, to be implemented and called for edge-cases with subclassing behavior (may be used for all subclass matching in the future)
> `OPERAS1Product` PGE V2.0.1 Subclassing Fix

- CHANGELOG.md
- asf_search/ASFProduct.py
- asf_search/Products/ARIAS1GUNWProduct.py
- asf_search/Products/OPERAS1Product.py
- asf_search/search/baseline_search.py
- asf_search/search/search_generator.py
- setup.py
- `OPERAS1Product` subclass now properly assigned to PGE v2.0.1 results
- `ARIAS1GUNWProduct.is_ARIAS1GUNWProduct()` removed, replaced with `ASFProduct._is_subclass()` implementation
> Release V7.1.2

- CHANGELOG.md
- asf_search/CMR/translate.py
From [Discovery Public](https://chat.asf.alaska.edu/asf/pl/snanijghqibhje4k3gdird44ey):
Second bullet on https://docs.python.org/3/whatsnew/3.12.html#other-language-changes
Python throws a warning on this line. Escaping the slash fixes it on 3.12.
```
>>> "\,"
<stdin>:1: SyntaxWarning: invalid escape sequence '\,'
'\\,'
>>> "\\,"
'\\,'
```
(Though they moved it from a DeprecationWarning to a SyntaxWarning. It might never become an error? This would silence the warning at least)
> Fix for python 3.12, escape characters throw warnings

- CHANGELOG.md
- asf_search/Products/ARIAS1GUNWProduct.py
- `ARIAS1GUNWProduct` uses `fileID` for `sceneName` if unpopulated
> Patch Release V8.2.1

- CHANGELOG.md
- asf_search/Products/ALOS2Product.py
- asf_search/Products/S1BurstProduct.py
- asf_search/export/jsonlite.py
- asf_search/export/jsonlite2.py
- asf_search/search/error_reporting.py
- asf_search/search/search.py
- asf_search/search/search_generator.py
- tests/yml_tests/test_search.yml
- `search()` no longer raises error if results are incomplete
- if `asf-search` receives an incomplete page from CMR, log as a warning and continue querying until results are exhausted
- `S1BurstProduct` No longer include null frame value in jsonlite outputs
- `S1BurstProduct` includes `SizeMB` in jsonlite outputs
- `ARIAVersion` now populated in jsonlite outputs
- `absoluteOrbit` field supports lists in jsonlite outputs
> V8.3.0 Minor Release

- CHANGELOG.md
- asf_search/export/json.py
- `json` output populates `relativeOrbit` field properly
> V9.0.7 Release

- CHANGELOG.md
- asf_search/CMR/datasets.py
- asf_search/constants/RANGE_BANDWIDTH.py
- Added NISAR L-SAR `RANGED_BANDWIDTH` constants `BW_20` and `BW_40`
- Added NISAR `GSLC` and `GUNW` `processingLevel` collection aliases
> Patch Release v9.0.9
