- setup.py
Reproducing changes from https://github.com/jhkennedy/Discovery-asf_search/pull/1 into asfadmin
> Distribution packages fixes

- CHANGELOG.md
- asf_search/search/baseline_search.py
- asf_search/search/geo_search.py
- asf_search/search/granule_search.py
- asf_search/search/product.py
- asf_search/search/product_search.py
- asf_search/search/results.py
- asf_search/search/search.py
- examples/hello_world.py
- ASFSearchResults now has a geojson() method which returns a data structure that matches the geojson specification
- ASFProduct now has a geojson() method that produces a data structure matching a geojson feature snippet
- ASFSearchResults and ASFProduct both have a __str__() methods that serializes the output of their geojson() methods
- ASFProduct is no longer a subclass of dict. Instead, metadata has been moved to .properties and .geometry
- ASFSearchResults is now a subclass of list, for list-like operations
> Feature core search

- .coveragerc
- .github/workflows/run-pytest.yml
- .gitignore
- README.md
Adds codecov badge (still points to fork), merging to get initial coverage report uploaded codecov
> Codecov Initialization

- asf_search/ASFSearchOptions/validator_map.py
- asf_search/constants/INTERNAL.py
- asf_search/search/geo_search.py
- asf_search/search/search.py
- asf_search/search/search_count.py
Reverts asfadmin/Discovery-asf_search#131
> Revert "Add beamSwath as a search parameter"

- asf_search/ASFSearchOptions/validator_map.py
- asf_search/constants/INTERNAL.py
- asf_search/search/geo_search.py
- asf_search/search/search.py
- asf_search/search/search_count.py
Reverts asfadmin/Discovery-asf_search#135
(see https://github.com/asfadmin/Discovery-asf_search/pull/131 for original)
> (re-merge) Add beamSwath as a search parameter

- CHANGELOG.md
- examples/1-Basic_Overview.ipynb
adds export format example in basic-overview jupyter notebook
> updates changelog, export-format examples

- CHANGELOG.md
- MANIFEST.in
- setup.py
Fixing template files being excluded from pypi distribution
> Setuptools bug fix

- CHANGELOG.md
- asf_search/ASFProduct.py
- asf_search/ASFSession.py
- asf_search/download/download.py
- Also fixes bad 401 Auth response when downloading with unauthenticated ASFSession
> Burst Product Download Default Filename

- CHANGELOG.md
- asf_search/download/download.py
- asf_search/search/search_generator.py
- tests/yml_tests/Resources/Fairbanks_S1_stack.yml
- tests/yml_tests/Resources/Fairbanks_SLC.yml
- Tenacity used for `search_generator()`, improving results polling
- TimeoutErrors now handled properly, logged
> adds tenacity to search_generator() cmr polling, Timeout Error Catching

- CHANGELOG.md
- asf_search/ASFSearchOptions/validator_map.py
- asf_search/CMR/field_map.py
- asf_search/CMR/subquery.py
- asf_search/search/search.py
- asf_search/search/search_generator.py
- Users can now narrow their results to a list of granule collections (concept-ids)
> Feature: Collections Search Keyword

- CHANGELOG.md
- asf_search/ASFSession.py
- asf_search/CMR/MissionList.py
- asf_search/constants/INTERNAL.py
- asf_search/search/error_reporting.py
moves error reporting url into INTERNAL.py as constants
> Topic: URL Constants

- CHANGELOG.md
- asf_search/ASFSession.py
- Adds configurable class variables to `ASFSession` class for previously constant values
- Moves `ASFSession` constant imports into constructor
> ASFSession Class Variables, Constant Import

- CHANGELOG.md
- asf_search/ASFProduct.py
- asf_search/Products/RADARSATProduct.py
- asf_search/Products/S1BurstProduct.py
- asf_search/Products/__init__.py
- asf_search/search/search_generator.py
- examples/Advanced-Custom-ASFProduct-Subclassing.ipynb
- S1BURSTProduct -> S1BurstProduct
- RadarsatProduct -> RADARSATProduct
> Acronym Capitalization

- CHANGELOG.md
- asf_search/search/search_generator.py
- OPERA-S1-CALIBRATION products now searchable again
- fixes edge-case when matching products to subclasses
> BUGFIX: OPERA-S1-CALIBRATION Dataset Product Search Error

- CHANGELOG.md
- asf_search/CMR/datasets.py
- asf_search/Products/ARIAS1GUNWProduct.py
- tests/yml_tests/test_search.yml
- adds ARIA_S1_GUNW dataset
- `inputGranules` and `ariaVersion` properties added to `ARIAS1GUNWProduct`
> ARIA_S1_GUNW Update

- CHANGELOG.md
- asf_search/ASFProduct.py
- asf_search/ASFSearchOptions/ASFSearchOptions.py
- asf_search/Products/ARIAS1GUNWProduct.py
- asf_search/Products/NISARProduct.py
- asf_search/Products/OPERAS1Product.py
- asf_search/WKT/RepairEntry.py
- asf_search/WKT/validate_wkt.py
- asf_search/search/search.py
- asf_search/search/search_generator.py
- `ASFProduct.get_sort_keys()` will no longer return `None` if missing sort keys, defaults to empty string 
- Platform used as final fallback criteria for subclass selection
- Improved logging in `search_generator()` and related methods
> Improved Debugging Support, ASFProduct Subclass Fallbacks

- setup.py
- dev status now Production/Stable
- adds  python versions 10-12 to supported versions list
> Update `setup.py` Status and Supported Versions

- CHANGELOG.md
- asf_search/Products/ALOS2Product.py
- Fix csv output for `ALOS2Product` type
> V8.2.3 Patch Release

- CHANGELOG.md
- asf_search/WKT/validate_wkt.py
- Doubled maximum number of iterations for geometry simplification from 10 to 20, allowing simplification of polygons with more points
> Patch Release 9.0.4

- CHANGELOG.md
- asf_search/ASFSearchResults.py
- asf_search/WKT/validate_wkt.py
- asf_search/export/__init__.py
- asf_search/export/json.py
Add missing json output format for SearchAPI V2/V3 parity
> Feat json output

- CHANGELOG.md
- asf_search/export/json.py
> Patch Release v9.0.6

- CHANGELOG.md
- asf_search/CMR/datasets.py
- Changed certain NISAR collection aliases to reference latest concept-ids
> Update nisar collection aliases

- CHANGELOG.md
- asf_search/CMR/datasets.py
- Changed certain NISAR collection aliases to reference latest concept-ids
> Patch Release 9.0.8

- CHANGELOG.md
- asf_search/Products/NISARProduct.py
- asf_search/export/jsonlite.py
[v10.0.1](https://github.com/asfadmin/Discovery-asf_search/compare/v10.0.0...v10.0.1)
- adds NISAR file sizes to the `nisar` attribute of exports
> NISAR file size export

- CHANGELOG.md
- asf_search/export/csv.py
- asf_search/export/kml.py
- asf_search/export/metalink.py
- Cleans up NISAR size display for csv/kml/metalink formats
> bug: fix NISAR size display for various output formats

- .github/workflows/prod-request-merged.yml
- CHANGELOG.md
- tests/yml_tests/Resources/ARIAS1GUNW_stack.yml
- Updated publish `action-create-release` github action to v3
- Updated ARIA test case
> Minor Release v10.1.0
